version: "2"
services:
    percona:
        image: percona/percona-server:latest
        environment:
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            # create volumes for use
            - db_logs:/var/log/mysql
            - db_data:/var/lib/mysql
            # bind mount my local my.cnf
            # - $PWD/my.cnf:/etc/my.cnf
        command:
            # Workaround for no my.cnf in image
            - '--user=mysql'
volumes:
    db_data:
        driver: local
    db_logs: {}
