version: "2"
services:
    db:
        image: percona/percona-server:latest
        environment:
            - MYSQL_ROOT_PASSWORD=secret
        ports:
            - "3306:3306"
        volumes:
            # create volumes for use
            - data:/var/lib/mysql
            - logs:/var/log
            # bind mount my local my.cnf
            # - $PWD/my.cnf:/etc/my.cnf
        networks:
            back-tier:
                aliases:
                    - mysql
        command:
            # Workaround for no my.cnf in image
            - '--user=mysql'
volumes:
    data:
        driver: local
    logs: {}
networks:
    back-tier:
        driver: bridge
