version: "2"
services:
    php:
        build: ./php55
        image: gcr.io/ste-optical-vts/php55
        environment:
            - MYSQL_ROOT_PASSWORD=secret
        volumes:
            - /var/www/html:/var/www/html
            - logs:/var/log
        tmpfs:
            - /tmp
        networks:
            front-tier:
                aliases:
                    - php
            back-tier:
    apache:
        build: .
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/www/html:/var/www/html
            - logs:/var/log
        tmpfs:
            - /tmp
        networks:
            - front-tier
volumes:
    logs: {}
networks:
    front-tier:
    back-tier:

