version: "2"
services:
    apache:
        build: .
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/www/html:/var/www/html
            - logs:/var/log
        networks:
            - front-tier
volumes:
    logs: {}
networks:
    front-tier:
        driver: overlay
