version: "2"
services:
    elasticsearch:
        image: million12/elasticsearch:1.4.4
        environment:
            - MARVEL_SUPPORT=true
            - ES_HEAP_SIZE=2g
        ports:
            - "9200:9200/tcp"
        volumes:
            - ./elasticsearch.in.sh:/opt/elasticsearch/bin/elasticsearch.in.sh
            - ./elasticsearch.yml:/opt/elasticsearch/config/elasticsearch.yml
        tmpfs:
            - /tmp
        expose:
            - "9200"
            - "9300"
