version: "2"
services:
    redis:
        image: centos/redis
        environment:
            - MASTER=true
        volumes:
            - redis-data:/var/lib/redis
            - logs:/var/log
        networks:
            - back-tier
        expose:
            - "6379"
volumes:
    redis_data:
        driver: local
    logs: {}
networks:
    back-tier:
        driver: overlay
