version: "2"
services:
    redis:
        image: centos/redis
        environment:
            - MASTER=true
        volumes:
            - redis-data:/var/lib/redis
        networks:
            - front-tier
        expose:
            - "6379"
networks:
    front-tier:
        driver: bridge
